# Testing the non-Markovian Path Analisys Package

We are going to generate first a MC trajectory of a toy model 

In [79]:
import numpy as np

from NMpathAnalysis.nmtools.interval import Interval
from src.trajectory import *

In [80]:
'''
Function to mimic a MC simulation
'''
def mc_simulation(numsteps):
    x = 5
    I = Interval([0,100])
    mc_traj = []
    
    for i in range(numsteps):
        dx = random.uniform(-10,10)
        if (x + dx) in I:
            x = x + dx
        mc_traj.append(x)
    return np.array(mc_traj)

In [81]:
'''
Simple mapping funcion to discreti
'''
def simple_mapping(x):
    return int(x/10)

In [82]:
#Generating a short MC trajectoy
mc_trajectory = mc_simulation(10000)


## 1-Trajectory class (analysis of continuos trajectories)

### Transition probabilities

In [85]:
t = Trajectory(mc_trajectory)

In [86]:
n_states = 10
C1 = t.count_matrix(n_states, simple_mapping)
print(C1)

[[ 702.  271.    0.    0.    0.    0.    0.    0.    0.    0.]
 [ 270.  620.  287.    0.    0.    0.    0.    0.    0.    0.]
 [   0.  286.  568.  269.    0.    0.    0.    0.    0.    0.]
 [   0.    0.  268.  485.  246.    0.    0.    0.    0.    0.]
 [   0.    0.    0.  245.  500.  236.    0.    0.    0.    0.]
 [   0.    0.    0.    0.  235.  432.  218.    0.    0.    0.]
 [   0.    0.    0.    0.    0.  217.  498.  247.    0.    0.]
 [   0.    0.    0.    0.    0.    0.  246.  449.  236.    0.]
 [   0.    0.    0.    0.    0.    0.    0.  236.  475.  245.]
 [   0.    0.    0.    0.    0.    0.    0.    0.  245.  767.]]


In [87]:
K1 = t._mle_transition_matrix(n_states, simple_mapping)
print(K1)

[[ 0.72147996  0.27852004  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.22939677  0.52676296  0.24384027  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.25467498  0.50578807  0.23953695  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.26826827  0.48548549  0.24624625  0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.24974516  0.509684    0.24057085
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.26553672  0.48813559
   0.24632768  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.22557173
   0.51767152  0.25675676  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.26423201  0.48227712  0.25349087  0.        ]
 [ 0.          0.          0.          0

### Defining states and computing MFPTs
The states are considered intervals in the continuous trajectory

In [88]:
stateA = [0,10]
stateB = [90,100]

t.mfpts(stateA, stateB)

{'mfptAB': 282.7894736842105,
 'mfptBA': 214.33333333333334,
 'std_err_mfptAB': 56.082427412945997,
 'std_err_mfptBA': 28.85393184153677}


## 2- DiscreteTrajectory class

We can generate a discrete trajectory from the same mapping function and we should obtain exaclty the same result:

In [90]:
dtraj = DiscreteTrajectory.from_continuous_traj(mc_trajectory,simple_mapping)

In [91]:
C2 = dtraj.count_matrix(n_states)
print(C2)

[[ 702.  271.    0.    0.    0.    0.    0.    0.    0.    0.]
 [ 270.  620.  287.    0.    0.    0.    0.    0.    0.    0.]
 [   0.  286.  568.  269.    0.    0.    0.    0.    0.    0.]
 [   0.    0.  268.  485.  246.    0.    0.    0.    0.    0.]
 [   0.    0.    0.  245.  500.  236.    0.    0.    0.    0.]
 [   0.    0.    0.    0.  235.  432.  218.    0.    0.    0.]
 [   0.    0.    0.    0.    0.  217.  498.  247.    0.    0.]
 [   0.    0.    0.    0.    0.    0.  246.  449.  236.    0.]
 [   0.    0.    0.    0.    0.    0.    0.  236.  475.  245.]
 [   0.    0.    0.    0.    0.    0.    0.    0.  245.  767.]]


In [92]:
K2= dtraj._mle_transition_matrix(n_states)
print(K2)

[[ 0.72147996  0.27852004  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.22939677  0.52676296  0.24384027  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.25467498  0.50578807  0.23953695  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.26826827  0.48548549  0.24624625  0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.24974516  0.509684    0.24057085
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.26553672  0.48813559
   0.24632768  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.22557173
   0.51767152  0.25675676  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.26423201  0.48227712  0.25349087  0.        ]
 [ 0.          0.          0.          0

### Defining states and computing MFPTs
The states are now considered sets, defining the states as follow we should obtain the same results

In [93]:
stateA = [0]
stateB = [9]

dtraj.mfpts(stateA, stateB)

{'mfptAB': 282.7894736842105,
 'mfptBA': 214.33333333333334,
 'std_err_mfptAB': 56.082427412945997,
 'std_err_mfptBA': 28.85393184153677}

The main function of this class would be to generate trajectories from the transition matrix

In [98]:
dtraj2 = DiscreteTrajectory.from_transition_matrix(K2,sim_length = 10000)

In [99]:
dtraj2.mfpts(stateA,stateB)

{'mfptAB': 186.07692307692307,
 'mfptBA': 193.73076923076923,
 'std_err_mfptAB': 29.832963137722267,
 'std_err_mfptBA': 31.840465754204942}